<br /><h4>   
NO INTRODUZCA AQUi EL CoDIGO DE SU APLICACIoN PORQUE EL CONTENIDO DE ESTE<br />
ARCHIVO SE CREARa DE MANERA AUTOMaTICA CUANDO SE GENERE LA APLICACIoN Y SE<br />
ELIMINARa CUALQUIER MODIFICACIoN QUE CONTENGA.<br />
<br />
EN LAS PROPIEDADES DEL PROYECTO PUEDE INDICAR CUAL SERa LA PaGINA DE INICIO<br />
DE SU APLICACIoN.</h4>